### PR TITLE
Various Fixes

### LINKED ISSUE #7: Hex Notebook is not craftable
The Hex Notebook should be craftable via a Book and Amethyst Dust (shapeless) but it is not. This is the error that is generated explaining why the recipe is not working properly.
```
[13:51:55] [main/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe hexcasting:patchi_book
com.google.gson.JsonParseException: Unknown registry key in ResourceKey[minecraft:root / minecraft:recipe_serializer]: patchouli:shapeless_book_recipe
        at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23100!/:?] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java:60) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java:36) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$1(SimplePreparableReloadListener.java:19) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:762) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526) ~[?:?] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.Util.blockUntilDone(Util.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.Util.blockUntilDone(Util.java:861) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:204) ~[server-1.21.1-20240808.144430-srg.jar%23128!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@4.0.41/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.41.jar%2359!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.41/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.41.jar%2359!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.41/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.41.jar%2359!/:4.0] {}
        at MC-BOOTSTRAP/fml_loader@4.0.41/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.41.jar%2359!/:4.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.5.jar%2364!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.5.jar%2364!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.5.jar%2364!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.5.jar%2364!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.5.jar%2364!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.5.jar%2364!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.5/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.5.jar%2364!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
```

### PR DESCRIPTION
**Pull request by Sirius902**
Closes #7.

Fixes the following:
* Slate not receiving patterns written to it and slate block entities not dropping an item with the written pattern on it.
* `SpellContinuation` serialization failing for `NotDone`.
* Fix Hex Notebook recipe failing to load.
* Fix `BlockEntityAbstractImpetus` `displayItem` serialization

Disclaimer: I have no clue what I'm doing when it comes to Minecraft modding, let me know if anything is terrible.

### CODE REVIEW

**Comment by s5bug** [comment]
I also wrote a fix for Jump iota serialization 🙇

File: src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt [hunk 1]
```diff
@@ -20,42 +13,38 @@ sealed interface SpellContinuation {
...
-                alternative
-            ).map<T>(
-                Function { either: Either<T, T> -> Either.unwrap(either) },
-                Function { value: T -> Either.left(value) }
-            )
+        fun toList(continuation: SpellContinuation): List<ContinuationFrame> {
+            val accumulator = ArrayList<ContinuationFrame>()
+            var c = continuation
+            while (c != Done) {
+                accumulator.add((c as NotDone).frame)
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt:29]: (Nitpick)
Check `is NotDone` like in pre-1.21 hexcasting would allow to avoid casting here
https://github.com/FallingColors/HexMod/blob/5da1bf82464d82aa303020e3fdf1fca17b9055d1/Common/src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt#L25-L26
Not really critical, so eh, replace if you want, or just mark as resolved

File: src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt [hunk 2]
```diff
@@ -20,42 +13,38 @@ sealed interface SpellContinuation {
...
+                c = c.next
+            }
+            return accumulator
         }
+
+        // TODO port: maybe unit should be first
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt:35]: Comment was left due to my Codec shenanigans, lol :p
Could be removed now

File: src/main/java/at/petrak/hexcasting/common/blocks/circles/BlockEntitySlate.java [hunk 3]
```diff
@@ -21,6 +25,19 @@ public BlockEntitySlate(BlockPos pos, BlockState state) {
...
+    @Override
+    protected void collectImplicitComponents(DataComponentMap.Builder components) {
+        super.collectImplicitComponents(components);
+        if (this.pattern != null) {
+            var tag = new CompoundTag();
+            tag.putString("id", HexAPI.modLoc("slate").toString());
+            tag.put(TAG_PATTERN, HexPattern.CODEC
+                    .encodeStart(NbtOps.INSTANCE, this.pattern)
+                    .getOrThrow());
+            components.set(DataComponents.BLOCK_ENTITY_DATA, CustomData.of(tag));
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/common/blocks/circles/BlockEntitySlate.java:37]: Is there any reason to use `BlockEntityData` instead of custom data component here?
You can save it to `ItemStack` via this method, and load it from `ItemStack` via `applyImplicitComponents`. I think it would be nicer

File: src/main/resources/data/hexcasting/recipe/patchi_book.json [hunk 4]
```diff
@@ -8,5 +8,11 @@
       "item": "hexcasting:amethyst_dust"
     }
   ],
-  "book": "hexcasting:thehexbook"
+  "result": {
+    "components": {
+      "patchouli:book": "hexcasting:thehexbook"
+    },
+    "count": 1,
```
Comment (slava110) [inline src/main/resources/data/hexcasting/recipe/patchi_book.json:15]: (Nitpick)
`count: 1` is redundant, you can remove it or simply mark it as resolved if you don't want to

**Review by slava110 — COMMENTED** [review]
Reviewed. Some comments are just nitpicks you can instantly mark as resolved if you want, but I'm not sure about saving blockentitydata stuff

File: src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt (hunk 1 above)
Comment (s5bug) [reply src/main/java/at/petrak/hexcasting/api/casting/eval/vm/SpellContinuation.kt:29]: I explicitly chose `c != Done` because it _should_ just resolve to a reference check rather than a class check (`Done` being an `object`). `is NotDone` is probably better for future readability so I'll discuss it with Sirius

File: src/main/java/at/petrak/hexcasting/common/blocks/circles/BlockEntitySlate.java (hunk 3 above)
Comment (Sirius902) [reply src/main/java/at/petrak/hexcasting/common/blocks/circles/BlockEntitySlate.java:37]: Oh I just used `BlockEntityData` because that looks like what was intended to be used in the prior `ItemSlate` implementation. Are you saying that the `collectImplicitComponents` implementation should update the `BlockEntityData` to add the `TAG_PATTERN` like is done here for `ItemSlate` https://github.com/slava110/NeoHexCasting/blob/022e83e229461e12accb255d77a46dd025559637/src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java#L119-L127 or are you suggesting to completely circumvent `BlockEntityData` altogether and make a different data component with `TAG_PATTERN` on it for both the `ItemSlate` and `BlockEntitySlate`?

Comment (Sirius902) [reply src/main/java/at/petrak/hexcasting/common/blocks/circles/BlockEntitySlate.java]: Actually I think I saw what you meant to do here, went ahead and fixed it! Definitely looks a lot cleaner.

File: src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java [hunk 5]
```diff
@@ -65,30 +60,21 @@ public static boolean hasPattern(ItemStack stack) {
...
         return false;
     }
 
     @Override
     public void inventoryTick(ItemStack pStack, Level pLevel, Entity pEntity, int pSlotId, boolean pIsSelected) {
         if (!hasPattern(pStack)) {
-            pStack.remove(DataComponents.BLOCK_ENTITY_DATA);
+            pStack.remove(HexDataComponents.PATTERN);
         }
     }
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java:73]: Looks redundant with datacomponents?

File: src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java [hunk 6]
```diff
@@ -65,30 +60,21 @@ public static boolean hasPattern(ItemStack stack) {
     @SoftImplement("IForgeItem")
     public boolean onEntityItemUpdate(ItemStack stack, ItemEntity entity) {
         if (!hasPattern(stack)) {
-            stack.remove(DataComponents.BLOCK_ENTITY_DATA);
+            stack.remove(HexDataComponents.PATTERN);
         }
         return false;
     }
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java:66]: Looks redundant with datacomponents?

File: src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java [hunk 7]
```diff
@@ -49,13 +50,7 @@ public Component getName(ItemStack pStack) {
...
-
-        if (bet != null && bet.contains(BlockEntitySlate.TAG_PATTERN)) {
-            var pattern = bet.read(HexPattern.CODEC.fieldOf(BlockEntitySlate.TAG_PATTERN)).result().orElse(null);
-            return Optional.ofNullable(pattern);
-        }
-        return Optional.empty();
+        return Optional.ofNullable(stack.get(HexDataComponents.PATTERN));
     }
 
     public static boolean hasPattern(ItemStack stack) {
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java:56]: This method might become unused after removing methods below

File: src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java [hunk 8]
```diff
@@ -49,13 +50,7 @@ public Component getName(ItemStack pStack) {
...
     public static Optional<HexPattern> getPattern(ItemStack stack){
-        var bet = stack.get(DataComponents.BLOCK_ENTITY_DATA);
-
-        if (bet != null && bet.contains(BlockEntitySlate.TAG_PATTERN)) {
-            var pattern = bet.read(HexPattern.CODEC.fieldOf(BlockEntitySlate.TAG_PATTERN)).result().orElse(null);
-            return Optional.ofNullable(pattern);
-        }
-        return Optional.empty();
+        return Optional.ofNullable(stack.get(HexDataComponents.PATTERN));
     }
```
Comment (slava110) [inline src/main/java/at/petrak/hexcasting/common/items/storage/ItemSlate.java:54]: Looks redundant with datacomponents

**Review by slava110 — COMMENTED** [review]
There are redundant methods there, You can remove them or mark everything as resolved and I'll merge and remove them myself (since it's probably annoying to make changes again, sorry)

**Comment by slava110** [comment]
I've also invited you to the repo so you could make changes, fix bugs, make releases, maybe add build pipeline without my explicit approval. You seem like a nice people knowing what they're doing c:

**Comment by Sirius902** [comment]
> I've also invited you to the repo so you could make changes, fix bugs, make releases, maybe add build pipeline without my explicit approval. You seem like a nice people knowing what they're doing c:

Thanks! Will use this power responsibly. Hex Casting is one of my favorite mods and I'm happy to help make sure it's ready for 1.21, I'll still probably need some help on the NeoForge side of things though. I'm currently testing this out on a modded server and @s5bug likes to do crazy stuff with Hex Casting so we won't have too hard of a time finding bugs I think.
